### ISSUE TITLE
Placeholders aren't working

### ISSUE THREAD

**Issue by Adriianh** [Neige7/NeigeItems-Kotlin#2]
**Versions**
  - PlaceholderAPI: 2.11.2
  - NeigeItems: Latest
  - Server: 1.19.2

**Issue**
I'm trying to use the placeholders but they don't seem to work, they don't return anything. I tried using the example item but they don't work either.

(ExampleItem4)
![image](https://user-images.githubusercontent.com/65142788/207710457-badb4124-1ac8-4e84-b1d2-25a5d1534f70.png)

**Comment by Adriianh** [comment]
Uh, it looks like it was a PlaceholderAPI problem. After a reboot it works fine, sorry for the inconvenience.

**Comment by Neige7** [comment]
The %neigeitems_XXXXX% was not PlaceholderAPI's placeholder. It is Item Placeholder. %ni_XXXXXX% is the papi placeholder. Please see Wiki for more information.
